### ISSUE TITLE
[Question] No update to Fatigue status

### ISSUE THREAD

**Issue by vavavr00m** [kkkingim/SimpleStatus#3]
As you can see in the screenshot below, the character is already feeling fatigue but the bar is still zero.

![image](https://user-images.githubusercontent.com/4675132/195965233-ac862dc4-ed8b-45e1-a48d-170fe27feac0.png)

**Comment by kkkingim** [comment]
this Fatigue is not Exercise Fatigue, if you enabled Sleep needed and Sleep allowed, then the Fatigue will increase
Exercise Fatigue is Body Damage, it's the body parts' property

**Comment by vavavr00m** [comment]
Oh I get it now. Sleep is disabled in the server I'm in. Thanks. Is it a good idea to change the description to "Sleep Fatigue" to avoid confusion?
